/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Stream */
        post: operations["chat_stream_api_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_admin_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_api_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: operations["list_all_api_conversations_get"];
        put?: never;
        /** Create */
        post: operations["create_api_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conv_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: operations["get_api_conversations__conv_id__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_conversations__conv_id__delete"];
        options?: never;
        head?: never;
        /** Update */
        patch: operations["update_api_conversations__conv_id__patch"];
        trace?: never;
    };
    "/api/conversations/batch-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete Batch
         * @description 批量删除多个对话。
         */
        post: operations["delete_batch_api_conversations_batch_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conv_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages_api_conversations__conv_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conv_id}/pin-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pin State */
        get: operations["get_pin_state_api_conversations__conv_id__pin_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conv_id}/messages/{msg_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Feedback */
        post: operations["feedback_api_conversations__conv_id__messages__msg_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conv_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_api_conversations__conv_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_documents_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/check-source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Source
         * @description Check if a source name already exists, without modifying any data.
         */
        get: operations["check_source_api_documents_check_source_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/upload-stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload File Stream
         * @description SSE streaming upload — sends progress events during ingestion.
         */
        post: operations["upload_file_stream_api_documents_upload_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/ingest-url-stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Url Stream
         * @description SSE streaming URL ingestion — sends progress events.
         */
        post: operations["ingest_url_stream_api_documents_ingest_url_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload File */
        post: operations["upload_file_api_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/ingest-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Url */
        post: operations["ingest_url_api_documents_ingest_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/import-demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Demo Documents */
        post: operations["import_demo_documents_api_documents_import_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/source/{source_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Source */
        delete: operations["delete_source_api_documents_source__source_name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear Kb */
        post: operations["clear_kb_api_documents_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-base/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_api_knowledge_base_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-base/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chunks */
        get: operations["chunks_api_knowledge_base_chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-base/chunks/{chunk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chunk By Id */
        get: operations["chunk_by_id_api_knowledge_base_chunks__chunk_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-base/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Source Names */
        get: operations["list_source_names_api_knowledge_base_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-base/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kb Config */
        get: operations["kb_config_api_knowledge_base_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-base/hotspots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hotspots */
        get: operations["hotspots_api_knowledge_base_hotspots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-base/debug-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Debug Search
         * @description Run a debug hybrid search that returns per-document scores (vector, BM25, RRF).
         */
        post: operations["debug_search_api_knowledge_base_debug_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: operations["list_all_api_workspaces_get"];
        put?: never;
        /** Create */
        post: operations["create_api_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{ws_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_workspaces__ws_id__delete"];
        options?: never;
        head?: never;
        /** Update */
        patch: operations["update_api_workspaces__ws_id__patch"];
        trace?: never;
    };
    "/api/workspaces/{ws_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_api_workspaces__ws_id__members_get"];
        /** Replace Members */
        put: operations["replace_members_api_workspaces__ws_id__members_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: operations["list_all_api_bookmarks_get"];
        put?: never;
        /** Create */
        post: operations["create_api_bookmarks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookmarks/{bookmark_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_bookmarks__bookmark_id__delete"];
        options?: never;
        head?: never;
        /** Update */
        patch: operations["update_api_bookmarks__bookmark_id__patch"];
        trace?: never;
    };
    "/api/metrics/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query Logs */
        get: operations["query_logs_api_metrics_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/logs/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Clear Today */
        delete: operations["clear_today_api_metrics_logs_today_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Return all user-facing configuration settings.
         */
        get: operations["get_settings_api_settings_get"];
        /**
         * Update Settings
         * @description Update runtime configuration. Only known keys are accepted.
         */
        put: operations["update_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminUserCreate */
        AdminUserCreate: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Role
             * @default viewer
             */
            role: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** AdminUserUpdate */
        AdminUserUpdate: {
            /** Username */
            username?: string | null;
            /** Password */
            password?: string | null;
            /** Role */
            role?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** AuthSessionOut */
        AuthSessionOut: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
            user: components["schemas"]["UserOut"];
        };
        /** Body_upload_file_api_documents_upload_post */
        Body_upload_file_api_documents_upload_post: {
            /** File */
            file: string;
        };
        /** Body_upload_file_stream_api_documents_upload_stream_post */
        Body_upload_file_stream_api_documents_upload_stream_post: {
            /** File */
            file: string;
        };
        /** BookmarkCreate */
        BookmarkCreate: {
            /**
             * Workspace Id
             * @default
             */
            workspace_id: string;
            /**
             * Conversation Id
             * @default
             */
            conversation_id: string;
            /**
             * Message Id
             * @default 0
             */
            message_id: number;
            /**
             * Chunk Id
             * @default
             */
            chunk_id: string;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Content
             * @default
             */
            content: string;
            /**
             * Source
             * @default
             */
            source: string;
            /**
             * Tags
             * @default
             */
            tags: string;
        };
        /** BookmarkOut */
        BookmarkOut: {
            /** Id */
            id: number;
            /** Workspace Id */
            workspace_id: string;
            /** Conversation Id */
            conversation_id: string;
            /** Message Id */
            message_id: number;
            /** Chunk Id */
            chunk_id: string;
            /** Note */
            note: string;
            /** Content */
            content: string;
            /** Source */
            source: string;
            /**
             * Tags
             * @default
             */
            tags: string;
            /** Created At */
            created_at: string;
        };
        /** BookmarkUpdate */
        BookmarkUpdate: {
            /** Note */
            note?: string | null;
            /** Tags */
            tags?: string | null;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Question */
            question: string;
            /** Thread Id */
            thread_id?: string | null;
            /**
             * Web Search Enabled
             * @default false
             */
            web_search_enabled: boolean;
            /**
             * Search Strategy
             * @default balanced
             */
            search_strategy: string;
            /** Pinned Chunk Ids */
            pinned_chunk_ids?: string[];
            /** Excluded Chunk Ids */
            excluded_chunk_ids?: string[];
            /**
             * Workspace Id
             * @default
             */
            workspace_id: string;
        };
        /** ChatSource */
        ChatSource: {
            /** Source */
            source: string;
            /** Chunk Id */
            chunk_id?: string | null;
            /** Chunk Index */
            chunk_index?: number | null;
            /** Page */
            page?: number | null;
            /** Score */
            score?: number | null;
            /** Content */
            content: string;
            /** Url */
            url?: string | null;
            /** Index */
            index?: number | null;
        };
        /** ConversationCreate */
        ConversationCreate: {
            /**
             * Title
             * @default 新对话
             */
            title: string;
        };
        /** ConversationOut */
        ConversationOut: {
            /** Id */
            id: string;
            /** Thread Id */
            thread_id: string;
            /** Title */
            title: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /**
             * Last Message Preview
             * @default
             */
            last_message_preview: string;
        };
        /** DebugSearchRequest */
        DebugSearchRequest: {
            /** Query */
            query: string;
            /**
             * K
             * @default 5
             */
            k: number;
            /**
             * Search Strategy
             * @default balanced
             */
            search_strategy: string;
        };
        /** DebugSearchResponse */
        DebugSearchResponse: {
            /** Strategy */
            strategy: string;
            /** Vector Results */
            vector_results: components["schemas"]["DebugSearchResult"][];
            /** Bm25 Results */
            bm25_results: components["schemas"]["DebugSearchResult"][];
            /** Fused Results */
            fused_results: components["schemas"]["DebugSearchResult"][];
        };
        /** DebugSearchResult */
        DebugSearchResult: {
            /** Chunk Id */
            chunk_id: string;
            /** Source */
            source: string;
            /** Content */
            content: string;
            /** Score */
            score?: number | null;
            /** Vector Score */
            vector_score?: number | null;
            /** Bm25 Score */
            bm25_score?: number | null;
            /** Rrf Score */
            rrf_score?: number | null;
            /** Vector Rank */
            vector_rank?: number | null;
            /** Bm25 Rank */
            bm25_rank?: number | null;
            /** Rrf Rank */
            rrf_rank?: number | null;
            /** Rerank Rank */
            rerank_rank?: number | null;
        };
        /** DemoImportResponse */
        DemoImportResponse: {
            /** Chunk Count */
            chunk_count: number;
            /** Total Docs */
            total_docs: number;
            /** Message */
            message: string;
            /** Imported Sources */
            imported_sources?: string[];
            /** Suggested Questions */
            suggested_questions?: string[];
        };
        /** ExportOut */
        ExportOut: {
            /**
             * Markdown
             * @default
             */
            markdown: string;
            /** Json */
            json?: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HotspotEntry */
        HotspotEntry: {
            /** Chunk Id */
            chunk_id: string;
            /** Source */
            source: string;
            /** Hits */
            hits: number;
            /** Content Preview */
            content_preview: string;
        };
        /** IngestResponse */
        IngestResponse: {
            /** Chunk Count */
            chunk_count: number;
            /** Total Docs */
            total_docs: number;
            /** Message */
            message: string;
            /** Suggested Questions */
            suggested_questions?: string[];
            /**
             * Existing Version
             * @default false
             */
            existing_version: boolean;
        };
        /** JobOut */
        JobOut: {
            /** Id */
            id: string;
            /** Job Type */
            job_type: string;
            /** Status */
            status: string;
            /** Created By User Id */
            created_by_user_id?: string | null;
            /**
             * Workspace Id
             * @default
             */
            workspace_id: string;
            progress?: components["schemas"]["JobProgress"];
            /**
             * Error
             * @default
             */
            error: string;
            /**
             * Attempts
             * @default 0
             */
            attempts: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
        };
        /** JobProgress */
        JobProgress: {
            /**
             * Phase
             * @default
             */
            phase: string;
            /**
             * Percent
             * @default 0
             */
            percent: number;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** KBChunk */
        KBChunk: {
            /** Source */
            source: string;
            /** Chunk Index */
            chunk_index: number;
            /** Chunk Id */
            chunk_id: string;
            /** Page */
            page?: number | null;
            /** Content */
            content: string;
            /** Original Content */
            original_content?: string | null;
            /** Section */
            section?: string | null;
        };
        /**
         * KBConfig
         * @description Knowledge base configuration returned by GET /api/knowledge-base/config.
         */
        KBConfig: {
            /** Chunk Size */
            chunk_size: number;
            /** Chunk Overlap */
            chunk_overlap: number;
        };
        /** KBStats */
        KBStats: {
            /** Chunk Count */
            chunk_count: number;
            /** Source Count */
            source_count: number;
            /** Total Chars */
            total_chars: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LogoutRequest */
        LogoutRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** MessageFeedback */
        MessageFeedback: {
            /** Feedback */
            feedback: string;
            /** Category */
            category?: string | null;
            /** Detail */
            detail?: string | null;
        };
        /** MessageOut */
        MessageOut: {
            /** Id */
            id: number;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Sources */
            sources?: components["schemas"]["ChatSource"][];
            /**
             * Quality Reason
             * @default
             */
            quality_reason: string;
            /** Debug Info */
            debug_info?: {
                [key: string]: unknown;
            };
            /** Feedback */
            feedback?: string | null;
            /** Created At */
            created_at: string;
        };
        /** PinStateOut */
        PinStateOut: {
            /** Thread Id */
            thread_id: string;
            /** Pinned Chunk Ids */
            pinned_chunk_ids?: string[];
            /** Excluded Chunk Ids */
            excluded_chunk_ids?: string[];
        };
        /** QueryLogEntry */
        QueryLogEntry: {
            /** Timestamp */
            timestamp: string;
            /**
             * Thread Id
             * @default
             */
            thread_id: string;
            /** Question */
            question: string;
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Retrieval Count */
            retrieval_count: number;
            /** Quality Ok */
            quality_ok: boolean;
            /** Quality Reason */
            quality_reason: string;
            /** Used Web Search */
            used_web_search?: boolean | null;
            /** Used Rerank */
            used_rerank?: boolean | null;
            /**
             * Question Type
             * @default
             */
            question_type: string;
            /**
             * Retry Count
             * @default 0
             */
            retry_count: number;
            /**
             * Source Count
             * @default 0
             */
            source_count: number;
            /**
             * Answer Preview
             * @default
             */
            answer_preview: string;
            /**
             * Error
             * @default
             */
            error: string;
            /**
             * Ttfb Ms
             * @default 0
             */
            ttfb_ms: number;
            /**
             * First Token Ms
             * @default 0
             */
            first_token_ms: number;
            /** Token Count */
            token_count?: number | null;
            /** Prompt Tokens */
            prompt_tokens?: number | null;
            /** Completion Tokens */
            completion_tokens?: number | null;
            /** Llm Model */
            llm_model?: string | null;
            /** Estimated Cost */
            estimated_cost?: number | null;
        };
        /** QueryLogsResponse */
        QueryLogsResponse: {
            /** Logs */
            logs?: components["schemas"]["QueryLogEntry"][];
            /**
             * Total Cost
             * @default 0
             */
            total_cost: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
            /**
             * Total Prompt Tokens
             * @default 0
             */
            total_prompt_tokens: number;
            /**
             * Total Completion Tokens
             * @default 0
             */
            total_completion_tokens: number;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RuntimeSettingsOut */
        RuntimeSettingsOut: {
            /**
             * Siliconflow Api Key
             * @default
             */
            siliconflow_api_key: string;
            /**
             * Siliconflow Base Url
             * @default https://api.siliconflow.cn/v1
             */
            siliconflow_base_url: string;
            /**
             * Embedding Model
             * @default BAAI/bge-m3
             */
            embedding_model: string;
            /**
             * Llm Model
             * @default deepseek-ai/DeepSeek-V4-Flash
             */
            llm_model: string;
            /**
             * Llm Temperature
             * @default 0.3
             */
            llm_temperature: number;
            /**
             * Tavily Api Key
             * @default
             */
            tavily_api_key: string;
            /**
             * Api Key
             * @default
             */
            api_key: string;
            /**
             * Chunk Size
             * @default 1500
             */
            chunk_size: number;
            /**
             * Chunk Overlap
             * @default 50
             */
            chunk_overlap: number;
            /**
             * Top K Retrieval
             * @default 5
             */
            top_k_retrieval: number;
            /**
             * Top K Rerank
             * @default 3
             */
            top_k_rerank: number;
            /**
             * Enable Quality Check
             * @default true
             */
            enable_quality_check: boolean;
            /**
             * Enable Contextual Retrieval
             * @default true
             */
            enable_contextual_retrieval: boolean;
        };
        /** RuntimeSettingsUpdate */
        RuntimeSettingsUpdate: {
            /** Siliconflow Api Key */
            siliconflow_api_key?: string | null;
            /** Siliconflow Base Url */
            siliconflow_base_url?: string | null;
            /** Embedding Model */
            embedding_model?: string | null;
            /** Llm Model */
            llm_model?: string | null;
            /** Llm Temperature */
            llm_temperature?: number | null;
            /** Tavily Api Key */
            tavily_api_key?: string | null;
            /** Api Key */
            api_key?: string | null;
            /** Chunk Size */
            chunk_size?: number | null;
            /** Chunk Overlap */
            chunk_overlap?: number | null;
            /** Top K Retrieval */
            top_k_retrieval?: number | null;
            /** Top K Rerank */
            top_k_rerank?: number | null;
            /** Enable Quality Check */
            enable_quality_check?: boolean | null;
            /** Enable Contextual Retrieval */
            enable_contextual_retrieval?: boolean | null;
        };
        /** SettingsUpdateResult */
        SettingsUpdateResult: {
            /** Updated */
            updated: boolean;
            /** Warnings */
            warnings?: string[];
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * SourceOut
         * @description Document source summary returned by GET /api/documents/sources.
         */
        SourceOut: {
            /** Source */
            source: string;
            /** Count */
            count: number;
        };
        /** URLIngestRequest */
        URLIngestRequest: {
            /**
             * Url
             * @description Public URL to fetch and ingest
             */
            url: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkspaceCreate */
        WorkspaceCreate: {
            /**
             * Name
             * @default 新工作区
             */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** WorkspaceMemberIn */
        WorkspaceMemberIn: {
            /** User Id */
            user_id: string;
            /** Role */
            role: string;
        };
        /** WorkspaceMemberOut */
        WorkspaceMemberOut: {
            /** Id */
            id: number;
            /** Workspace Id */
            workspace_id: string;
            /** User Id */
            user_id: string;
            /** Username */
            username: string;
            /** Role */
            role: string;
            /** Created At */
            created_at: string;
        };
        /** WorkspaceMembersUpdate */
        WorkspaceMembersUpdate: {
            /** Members */
            members?: components["schemas"]["WorkspaceMemberIn"][];
        };
        /** WorkspaceOut */
        WorkspaceOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** WorkspaceUpdate */
        WorkspaceUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat_stream_api_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 请求过于频繁 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_users_api_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    create_user_api_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_admin_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_api_conversations_get: {
        parameters: {
            query?: {
                workspace_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_conversations_post: {
        parameters: {
            query?: {
                workspace_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConversationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_api_conversations__conv_id__get: {
        parameters: {
            query?: {
                workspace_id?: string | null;
            };
            header?: never;
            path: {
                conv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_conversations__conv_id__delete: {
        parameters: {
            query?: {
                workspace_id?: string | null;
            };
            header?: never;
            path: {
                conv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_conversations__conv_id__patch: {
        parameters: {
            query?: {
                workspace_id?: string | null;
            };
            header?: never;
            path: {
                conv_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_batch_api_conversations_batch_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_api_conversations__conv_id__messages_get: {
        parameters: {
            query?: {
                workspace_id?: string | null;
            };
            header?: never;
            path: {
                conv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pin_state_api_conversations__conv_id__pin_state_get: {
        parameters: {
            query?: {
                workspace_id?: string | null;
            };
            header?: never;
            path: {
                conv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_api_conversations__conv_id__messages__msg_id__feedback_post: {
        parameters: {
            query?: {
                workspace_id?: string | null;
            };
            header?: never;
            path: {
                conv_id: string;
                msg_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageFeedback"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_conversations__conv_id__export_get: {
        parameters: {
            query?: {
                format?: string;
                include_sources?: boolean;
                include_debug?: boolean;
                workspace_id?: string | null;
            };
            header?: never;
            path: {
                conv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_documents_sources_get: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_source_api_documents_check_source_get: {
        parameters: {
            query: {
                source_name: string;
                workspace_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_stream_api_documents_upload_stream_post: {
        parameters: {
            query?: {
                version_mode?: string | null;
                workspace_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_stream_api_documents_upload_stream_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 请求过于频繁 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ingest_url_stream_api_documents_ingest_url_stream_post: {
        parameters: {
            query?: {
                version_mode?: string | null;
                workspace_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["URLIngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 请求过于频繁 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upload_file_api_documents_upload_post: {
        parameters: {
            query?: {
                version_mode?: string | null;
                workspace_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_api_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 请求过于频繁 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ingest_url_api_documents_ingest_url_post: {
        parameters: {
            query?: {
                version_mode?: string | null;
                workspace_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["URLIngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 请求过于频繁 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    import_demo_documents_api_documents_import_demo_post: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_source_api_documents_source__source_name__delete: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path: {
                source_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_kb_api_documents_clear_post: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_api_knowledge_base_stats_get: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KBStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chunks_api_knowledge_base_chunks_get: {
        parameters: {
            query?: {
                source?: string;
                search?: string;
                skip?: number;
                limit?: number;
                workspace_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chunk_by_id_api_knowledge_base_chunks__chunk_id__get: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path: {
                chunk_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Source */
                        source: string;
                        /** Chunk Index */
                        chunk_index: number;
                        /** Chunk Id */
                        chunk_id: string;
                        /** Page */
                        page?: number | null;
                        /** Content */
                        content: string;
                        /** Original Content */
                        original_content?: string | null;
                        /** Section */
                        section?: string | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_source_names_api_knowledge_base_sources_get: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kb_config_api_knowledge_base_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KBConfig"];
                };
            };
        };
    };
    hotspots_api_knowledge_base_hotspots_get: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotspotEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_search_api_knowledge_base_debug_search_post: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DebugSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebugSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_api_workspaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"][];
                };
            };
        };
    };
    create_api_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_workspaces__ws_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_workspaces__ws_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_workspaces__ws_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_members_api_workspaces__ws_id__members_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceMembersUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_api_bookmarks_get: {
        parameters: {
            query?: {
                workspace_id?: string | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_bookmarks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookmarkCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_bookmarks__bookmark_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookmark_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_bookmarks__bookmark_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookmark_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookmarkUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_logs_api_metrics_logs_get: {
        parameters: {
            query?: {
                days?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryLogsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_today_api_metrics_logs_today_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeSettingsOut"];
                };
            };
        };
    };
    update_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuntimeSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsUpdateResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
